build checks

diff --git a/lint-php-project/action.yml b/lint-php-project/action.yml
--- a/lint-php-project/action.yml
+++ b/lint-php-project/action.yml
@@ -25,7 +25,15 @@ runs:
       shell: bash
       run: |
         #
-        echo "${{fromJson(steps.set_var.outputs.composerJson).require['edact/e3t-php-api']}}"
+        if [[ "${{fromJson(steps.set_var.outputs.composerJson).require['edact/e3t-php-api']}}" != "dev/main" ]]; then
+          echo "::error title=Feature package version detected::The version of 'edact/e3t-php-api' must be 'dev/main'!"
+          exit 1
+        fi
+
+        if [[ "${{fromJson(steps.set_var.outputs.composerJson).require['edact/e3t-oas-components']}}" != "dev/main" ]]; then
+          echo "::error title=Feature package version detected::The version of 'edact/e3t-oas-components' must be 'dev/main'!"
+          exit 1
+        fi
 
     - name: install dependencies & run linter
       shell: bash
