>&2

diff --git a/run-docker-compose/action.yml b/run-docker-compose/action.yml
--- a/run-docker-compose/action.yml
+++ b/run-docker-compose/action.yml
@@ -55,10 +55,10 @@ runs:
               echo "::error::Limit of ${{ inputs.healthcheck_limit }} reached."
             fi
 
-            echo 'Health check failed, retrying in ${{ inputs.healthcheck_timeout }} seconds..'
+            echo >&2 'Health check failed, retrying in ${{ inputs.healthcheck_timeout }} seconds..'
             sleep ${{ inputs.healthcheck_timeout }}
 
             RETRIES=$RETRIES+1
         done
 
-        echo 'Health check succeeded.'
+        echo >&2 'Health check succeeded.'
