check package files (#18)
* try it

* syntax error

* move to action

* give names

* switch branch

* ''

* set title

* try other

* print

* #

* remove

* .require outside

* []

* build checks

* -

* point to main

diff --git a/check-npm-package/action.yml b/check-npm-package/action.yml
--- a/check-npm-package/action.yml
+++ b/check-npm-package/action.yml
@@ -5,6 +5,27 @@ author: "eDACT"
 runs:
   using: "composite"
   steps:
+    - name: Putting package.json in output variable
+      shell: bash
+      id: set_var
+      run: |
+        content=`cat package.json`
+        # the following lines are only required for multi line json
+        content="${content//'%'/'%25'}"
+        content="${content//$'\n'/'%0A'}"
+        content="${content//$'\r'/'%0D'}"
+        # end of optional handling for multi line json
+        echo "::set-output name=packageJson::$content"
+
+    - name: Evaluating npm entrypoint
+      shell: bash
+      run: |
+        #
+        if [[ "${{fromJson(steps.set_var.outputs.packageJson).main}}" != dist/* ]]; then
+          echo "::error title=Invalid package entrypoint::The field 'main' in the package.json must point to the 'dist/*' folder!"
+          exit 1
+        fi
+
     - shell: bash
       run: |
         #
