lint openapi

diff --git a/lint-openapi-spec/action.yml b/lint-openapi-spec/action.yml
--- a/lint-openapi-spec/action.yml
+++ b/lint-openapi-spec/action.yml
@@ -8,5 +8,22 @@ inputs:
     default: "src/public/openapi.yml"
 
 runs:
-  using: "docker"
-  image: "Dockerfile"
+  # using: "docker"
+  # image: "Dockerfile"
+  using: "composite"
+  steps:
+    - shell: bash
+      run: |
+        # makes the script existing once an error occours
+        set -euo pipefail
+
+        if [ ! -f "$INPUT_INPUT_PATH" ]; then
+            echo "::error::$INPUT_INPUT_PATH does not exist!"
+            exit 1
+        fi
+
+        # install
+        npm i @stoplight/spectral@^5.0.0 --global --quiet
+
+        # lint
+        spectral lint ${INPUT_INPUT_PATH} --skip-rule oas3-unused-components-schema
