replace container actions

diff --git a/lint-openapi-spec/action.yml b/lint-openapi-spec/action.yml
--- a/lint-openapi-spec/action.yml
+++ b/lint-openapi-spec/action.yml
@@ -11,4 +11,19 @@ runs:
   using: "composite"
   steps:
     - shell: bash
-      run: sh entrypoint.sh
+      run: |
+        # makes the script existing once an error occours
+        set -euo pipefail
+
+        if [ ! -f "${{ inputs.input_path }}" ]; then
+            echo "::error::${{ inputs.input_path }} does not exist!"
+            exit 1
+        fi
+
+        # install
+        npm i @stoplight/spectral@^5.0.0 --global --quiet
+
+        echo "::group::linting results"
+        # lint
+        spectral lint ${{ inputs.input_path }} --skip-rule oas3-unused-components-schema
+        echo "::endgroup::"
